### PR TITLE
Architecture revamp

### PR DESCRIPTION
**Pull request by alco**
This is where all the OTP goodness comes in.

So far the connection process has been rewritten to a GenServer and it works.

What's still left to do:

  * [x] Hook up the hook manager with the updated connection server. Hooks are no longer stored in the connection process but in a dedicated `HookManager` process. The connection should probably emit incoming messages as `GenEvent` events.

  * [x] The hook manager listens on events and processes them by invoking each hook in a separate `Task`. This approach leads to isolation of all of the system's components from each other so that one thing crashing doesn't have any adverse effects on the rest of the system.

### CODE REVIEW

**Comment by alco** [comment]
I have tested hooks from `beamie_bot` with this version of chatty and everything seems to work.

**Comment by Annwenn** [comment]
Okay :) I'll try it out with Alher and will send you feedback about what might go wrong.

**Comment by Annwenn** [comment]
So, do you plan something else before merging it with master? :)

**Comment by alco** [comment]
@Annwenn Yes, there are some TODO notes left in the code I'd like to address. Also need to update the docs.

Do you think you could help me with a test suite? I'm thinking some basic regression tests that check the hook API works on a mock connection. First I need to expose the ability to substitute the connection module. Then the tests can use the real hook manager and test that hooks are invoked when expected, that crash inside a hook doesn't affect other processes, etc.

**Comment by Annwenn** [comment]
@alco Oh, I know for a fact that Chatty is resilient enough now. [Alher](https://github.com/Queertoo/Alher) has been running on your last commit lately, and the hook crashes didn't kill the hook manager.
Of course I'd be glad to help :)

**Comment by Annwenn** [comment]
@alco Okay I can testify that we must set the timeout to at least 10 seconds for the hooks :)

**Comment by alco** [comment]
@Annwenn Hey. How does the 10-second delay in hook processing work out for you in terms of user experience? I would normally think the thing is broken if it didn't get back to me in a few seconds.

**Comment by alco** [comment]
Merging this to master. Will handle the remaining `TODO`s separately.

**Comment by Annwenn** [comment]
:+1:

**Comment by Annwenn** [comment]
>@Annwenn Hey. How does the 10-second delay in hook processing work out for you in terms of user experience? I would normally think the thing is broken if it didn't get back to me in a few seconds.

Well, some websites send large data that take some time to process. Parsing large JSON files or doing multiple http requests can take up to 6-7 seconds.

**Pull request merged**
