### PR TITLE
Additional hooks

### PR DESCRIPTION
**Pull request by alco**
There are some breaking changes in the way hooks are added.

I also changed the argument order to be similar regardless of the hook kind.

And also added the `channel` argument to `privmsg` hooks that wasn't there before.

Still left to do:

  * [ ] fix `FIXME`s in the code
  * [ ] make sure private messages work

@Annwenn, feedback welcome!

### CODE REVIEW

**Comment by Annwenn** [comment]
I think it's going to be awesome. I'll test some hooks tonight.

**Comment by Annwenn** [comment]
Concerning this [FIXME](https://github.com/alco/chatty/commit/9a3848f7a9ebf7e10d99b0d31b2231c9f3427f62#diff-2fce2c05862c8cb9d9e5ff550e501b44R151), are you targeting this function: https://github.com/alco/chatty/blob/additional-hooks/lib/chatty/hook_manager.ex#L103-L129 ?

**Comment by alco** [comment]
@Annwenn yes, some of those options don't make sense for presence hooks.

**Comment by alco** [comment]
I have tested this with hooks from beamie_bot and it seems to work. Merging this now, remaining issues will be addressed individually.

**Comment by alco** [comment]
Clarification: I've only tested `:privmsg` hooks with beamie_bot.

**Pull request merged**
